export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const LOAD_INGREDIENTS = 'LOAD_INGREDIENTS';
export const LOAD_INGREDIENTS_ERROR = 'LOAD_INGREDIENTS_ERROR';

export const BURGER_PURCHASE_SUCCESS = 'BURGER_PURCHASE_SUCCESS';
export const BURGER_PURCHASE_FAIL = 'BURGER_PURCHASE_FAIL';
export const BURGER_PURCHASE_ATTEMPT = 'BURGER_PURCHASE_ATTEMPT';
export const BURGER_PURCHASE_INIT = 'BURGER_PURCHASE_INIT';

export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_RESET_ERROR = 'AUTH_RESET_ERROR';

//SAGA POINTERS
export const INIT_CHECK_AUTH_STATUS = 'INIT_CHECK_AUTH_STATUS';
export const INIT_AUTH = 'INIT_AUTH';
export const INIT_AUTH_LOGOUT = 'INIT_AUTH_LOGOUT';
export const INIT_AUTH_SESS_LOGOUT = 'INIT_AUTH_SESS_LOGOUT';

export const INIT_BURGER_PURCHASE = 'INIT_BURGER_PURCHASE';
export const INIT_FETCH_ORDERS = 'INIT_FETCH_ORDERS';

export const INIT_SET_INGREDIENTS = 'INIT_SET_INGREDIENTS';







